# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 08:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='category_customer', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('priviledge', models.IntegerField(default=0)),
            ],
            options={
                'default_related_name': 'category_customer',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TalkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(db_index=True)),
                ('sid', models.IntegerField(db_index=True)),
                ('student_name', models.CharField(max_length=64)),
                ('student_sex', models.CharField(max_length=64)),
                ('student_class', models.CharField(max_length=64)),
                ('student_id', models.CharField(max_length=64)),
                ('student_policy_role', models.CharField(max_length=64)),
                ('student_nation', models.CharField(max_length=64)),
                ('student_dorm_address', models.TextField()),
                ('student_phonenumber', models.CharField(max_length=64)),
                ('student_dorm_phonenumber', models.CharField(max_length=64)),
                ('student_home_address', models.TextField()),
                ('student_home_phonenumber', models.CharField(max_length=64)),
                ('student_email', models.CharField(max_length=64)),
                ('student_home_situation', models.TextField()),
                ('student_study_situation', models.TextField()),
                ('student_thought_situation', models.TextField()),
                ('student_live_situation', models.TextField()),
                ('student_society_situation', models.TextField()),
                ('teacher_name', models.CharField(max_length=64)),
                ('talk_time', models.DateTimeField(null=True)),
                ('talk_place', models.TextField()),
                ('content', models.TextField()),
                ('recommend', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='category_student', serialize=False, to='category.CustomUser')),
                ('student_name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'default_related_name': 'category_student',
            },
            bases=('category.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='category_teacher', serialize=False, to='category.CustomUser')),
                ('student', models.ManyToManyField(related_name='category_teacher', to='category.Student')),
            ],
            options={
                'default_related_name': 'category_teacher',
            },
            bases=('category.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterIndexTogether(
            name='talkrecord',
            index_together=set([('tid', 'sid')]),
        ),
    ]
