# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('record', models.CharField(max_length=100)),
                ('next_advice', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
